### ISSUE TITLE
iOS 18 以上系统添加日历控件闪退，iOS 18 对 UIView.maskView 增加了断言，导致如果业务代码里有同名属性可能导致触发该断言

### ISSUE THREAD

**Issue by Kemenger** [Eafy/ZJBaseUtils_iOS#1]
iOS 18 以上系统添加日历控件闪退，iOS 18 对 UIView.maskView 增加了断言，导致如果业务代码里有同名属性可能导致触发该断言

**Comment by Eafy** [comment]
感谢反馈，现已兼容iOS 18，已发布版本[v1.5.4](https://github.com/Eafy/ZJBaseUtils_iOS/releases/tag/v1.5.4)
